### ISSUE TITLE
MiniProject : QR CODE

### ISSUE THREAD

**Issue by gdsc-mmcoe** [Google-Developer-Student-Club-CCOEW/Web-Development-2023-GDSC-CUMMINS-X-GDSC-MMCOE#48]
This web application project is designed to create a QR code generator that allows users to input text or URLs and generate QR codes for easy sharing. QR codes are a popular means of sharing information quickly and conveniently, and this project provides a simple and user-friendly tool for generating them.

### Contribute to the following folder
-[QR CODE](https://github.com/Google-Developer-Student-Club-CCOEW/Web-Development-2023-GDSC-CUMMINS-X-GDSC-MMCOE/tree/main/MiniProjects/QR%20CODE)

**Comment by gdsc-mmcoe** [comment]
📢 Announcement: Issue Assignment Starting Tomorrow

Dear contributors,

We're excited to kick off the assignment of issues for our project tomorrow. Your contributions are invaluable, and we appreciate your enthusiasm!

To ensure a smooth process, please make sure to follow the format and guidelines provided in the main repository description when submitting your requests. This helps us understand your contributions better and streamline the assignment process.

Thank you for your cooperation, and get ready to make a difference in our project!

Best regards,
Team GDSC MMCOE & Cummins

**Comment by Atharv-Nalwade** [comment]
I would like to solve this up 
Kindly assign it to me

**Comment by Atharv-Nalwade** [comment]
Also I wanted to bring a minor issue to your attention regarding the provided clone command for the GitHub repository. The command currently reads:
```
git clone https://github.com/yourusername/qr-code-generator-webapp.git
```
It appears that the placeholder "yourusername" may not be suitable for the intended purpose and could potentially cause confusion for users trying to clone the repository. To ensure a smoother experience for everyone, it would be greatly appreciated if you could update the command with the correct GitHub username.
Technically it should be this account's name

**Comment by sayli2003** [comment]
I would like to work on this issue!!
Can you assign this to me
-Sayli Borole
TY Comp, Cummins
