### ISSUE TITLE
MiniProject : Language Translation Web App

### ISSUE THREAD

**Issue by gdsc-mmcoe** [Google-Developer-Student-Club-CCOEW/Web-Development-2023-GDSC-CUMMINS-X-GDSC-MMCOE#49]
Break language barriers and communicate effortlessly with our Language Translation Web App. Translate text from one language to another in real time, making global communication a breeze. Simple, fast, and user-friendly.

### Contribute to the following folder

- [Language Translation Web App](https://github.com/Google-Developer-Student-Club-CCOEW/Web-Development-2023-GDSC-CUMMINS-X-GDSC-MMCOE/tree/main/MiniProjects/Language%20Translation%20Web%20App)

**Comment by gdsc-mmcoe** [comment]
📢 Announcement: Issue Assignment Starting Tomorrow

Dear contributors,

We're excited to kick off the assignment of issues for our project tomorrow. Your contributions are invaluable, and we appreciate your enthusiasm!

To ensure a smooth process, please make sure to follow the format and guidelines provided in the main repository description when submitting your requests. This helps us understand your contributions better and streamline the assignment process.

Thank you for your cooperation, and get ready to make a difference in our project!

Best regards,
Team GDSC MMCOE & Cummins

**Comment by Vasanthavel124** [comment]
can you assign this to me?

**Comment by gdsc-mmcoe** [comment]
@Atharv-Nalwade has Fixed this issue
