### ISSUE TITLE
MiniProject : Real-Time Chat Application

### ISSUE THREAD

**Issue by gdsc-mmcoe** [Google-Developer-Student-Club-CCOEW/Web-Development-2023-GDSC-CUMMINS-X-GDSC-MMCOE#51]
Stay connected and chat in real-time with friends, family, and colleagues using our intuitive Real-Time Chat App. Share messages, emojis, and more, making conversations feel closer than ever. Instant, reliable, and fun! 📱💬

### Contribute to the following folder

-[Chat App](https://github.com/Google-Developer-Student-Club-CCOEW/Web-Development-2023-GDSC-CUMMINS-X-GDSC-MMCOE/tree/main/MiniProjects/real-time%20chat%20application%20)

**Comment by gdsc-mmcoe** [comment]
📢 Announcement: Issue Assignment Starting Tomorrow

Dear contributors,

We're excited to kick off the assignment of issues for our project tomorrow. Your contributions are invaluable, and we appreciate your enthusiasm!

To ensure a smooth process, please make sure to follow the format and guidelines provided in the main repository description when submitting your requests. This helps us understand your contributions better and streamline the assignment process.

Thank you for your cooperation, and get ready to make a difference in our project!

Best regards,
Team GDSC MMCOE & Cummins

**Comment by Vasanthavel124** [comment]
can you assign this to me?

**Comment by gdsc-mmcoe** [comment]
@Vasanthavel124 you are assigned to this issue, Please Make a valid pull request asap
