### ISSUE TITLE
Not able to clone this GitHub repository ⚠️

### ISSUE THREAD

**Issue by Atharv-Nalwade** [Google-Developer-Student-Club-CCOEW/Web-Development-2023-GDSC-CUMMINS-X-GDSC-MMCOE#68]
Please find below the attached screenshot that will explain the error faced by me

![image](https://github.com/Google-Developer-Student-Club-CCOEW/Web-Development-2023-GDSC-CUMMINS-X-GDSC-MMCOE/assets/98139553/476c535d-ae65-4a24-ab20-b5393589790c)

**Comment by Phenzic** [comment]
Been trying to do the same for a while now, 
Have you been assigned an Issue?

**Comment by gdsc-mmcoe** [comment]
@Atharv-Nalwade Great news! I've successfully resolved the repository cloning issue. 🚀🔧 Now, you should be able to clone the repository without any problems. If you encounter any other issues or need further assistance, please don't hesitate to let me know. Happy coding! 👨‍💻👩‍💻
