### ISSUE TITLE
Implement Teacher Login API

### ISSUE THREAD

**Issue by gdsc-mmcoe** [Google-Developer-Student-Club-CCOEW/Web-Development-2023-GDSC-CUMMINS-X-GDSC-MMCOE#8]
**Title:** 
Implement Teacher Login API🚀 

**Description:** 🚀 Create the backend API for teacher login. This API should authenticate teachers based on their email and password📊 based on schema of Teacher table which is defined in this [readme](https://github.com/Google-Developer-Student-Club-CCOEW/Web-Development-2023/blob/main/QR-Based-Attendence-System/readme.md) file. This issue is located [here](https://github.com/Google-Developer-Student-Club-CCOEW/Web-Development-2023/tree/main/QR-Based-Attendence-System/backend).

**Teachers login table schema:**
Email
Password

**Comment by capsy14** [comment]
Kindly assign this issue to me :)

**Comment by Ryrahul** [comment]
I can work on it can you assign it to me @gdsc-mmcoe

**Comment by gdsc-mmcoe** [comment]
📢 **Announcement: Issue Assignment Starting Tomorrow**

Dear contributors,

We're excited to kick off the assignment of issues for our project tomorrow. Your contributions are invaluable, and we appreciate your enthusiasm!

To ensure a smooth process, please make sure to follow the format and guidelines provided in the main repository description when submitting your requests. This helps us understand your contributions better and streamline the assignment process.

Thank you for your cooperation, and get ready to make a difference in our project!

Best regards,
Team GDSC MMCOE & Cummins

**Comment by Gdsc-Cummins** [comment]
@Ryrahul u can work on this issue, you have two days!

**Comment by Ryrahul** [comment]
I am not a  Cummins College and MMCOE student

**Comment by gdsc-mmcoe** [comment]
@Ryrahul No worry , you can work on this issue.
